### ISSUE TITLE
Publishing github release may fail

### ISSUE THREAD

**Issue by rpocase** [ADTRAN/gradle-betablocker-plugin#3]
On our initial release from travis, it hit a 404 when trying to query for releases. I wasn't able to reproduce this locally, so I drafted the release manually. Just plopping this here just in case it comes up again and we actually need to address it.

https://travis-ci.org/ADTRAN/gradle-betablocker-plugin/builds/383167004?utm_source=github_status&utm_medium=notification

**Comment by nathanalderson** [comment]
This appears to have happened [again](https://travis-ci.org/ADTRAN/gradle-betablocker-plugin/builds/445385173) with the merge of #5.

**Comment by rpocase** [comment]
I believe the issue is that (at a minimum) the github api key isn't configured correctly. I may need to reinject more than just that. I'll plan on getting a PR up either tomorrow or Monday.

**Comment by rpocase** [comment]
This was sillier than expected. I just forgot to give adtran-automation write permission to this repo. I'm still going to do a PR (with some other changes) to validate this

**Comment by nathanalderson** [comment]
Closing. Although #6 was not completed, it did verify that @rpocase fixed the underlying permission issue that caused this bug.
